fullnameOverride: "azureflaskapp"

image:
  repository: mycompanyapp.azurecr.io/az-sample-app
  tag: "v3"

serviceAccount:
  create: true
  annotations:
    azure.workload.identity/client-id: "XX-XXX-XXX-XXX-XXX"
  name: "flaskapp"

azure.workload.identity/use: "true"

tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"

service:
  type: ClusterIP
  port: 5000

container:
  env:
    - name: AZURE_SUBSCRIPTION_ID
      value: "XXXXX-XXXX-XXXX-XXXX-XXXXX"
    - name: AZURE_KEYVAULT_NAME
      value: "companyname0staging0secret"
    - name: AZURE_STORAGE_ACCOUNT
      value: "companyname0staging0app"
    - name: AZURE_CONTAINER_NAME
      value: "app-data"

ingress:
  enabled: false
  className: "azure-application-gateway"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: "*"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []